[package]
name = "one"
version = "0.1.0"
authors = ["Doug Zobel <zobel_junk@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
